import type { Project } from '../types'

export const PROJECTS: Project[] = [
  {
    id: 'kampala-commercial-tower',
    title: 'Kampala Commercial Tower',
    description: 'A 15-storey commercial office tower in the heart of Kampala featuring modern architecture, energy-efficient systems and premium office spaces.',
    category: 'Commercial',
    location: 'Kampala, Uganda',
    duration: '24 months',
    client: 'Kampala Properties Ltd',
    budget: '$15M',
    technologies: ['Reinforced Concrete', 'Curtain Wall Glazing', 'Smart Building Systems', 'Elevators'],
    images: ['/images/projects/placeholder.svg'],
    status: 'completed',
  },
  {
    id: 'entebbe-highway',
    title: 'Entebbe Express Highway',
    description: 'Construction of a 35km dual carriageway connecting Kampala to Entebbe International Airport, improving transportation efficiency.',
    category: 'Infrastructure',
    location: 'Kampala – Entebbe, Uganda',
    duration: '36 months',
    client: 'Uganda National Roads Authority',
    budget: '$85M',
    technologies: ['Asphalt Pavement', 'Bridge Structures', 'Drainage Systems', 'Road Signage'],
    images: ['/images/projects/placeholder.svg'],
    status: 'completed',
  },
  {
    id: 'nile-bridge',
    title: 'Jinja Nile Bridge',
    description: 'Design and construction of a modern cable-stayed bridge across the River Nile, enhancing connectivity between eastern and northern Uganda.',
    category: 'Infrastructure',
    location: 'Jinja, Uganda',
    duration: '30 months',
    client: 'Ministry of Works & Transport',
    budget: '$45M',
    technologies: ['Cable-Stayed Structure', 'Pile Foundation', 'Prestressed Concrete', 'Expansion Joints'],
    images: ['/images/projects/placeholder.svg'],
    status: 'completed',
  },
  {
    id: 'nakasero-residential',
    title: 'Nakasero Luxury Residences',
    description: 'Premium residential development featuring 50 luxury apartments with modern amenities and panoramic city views.',
    category: 'Residential',
    location: 'Nakasero, Kampala',
    duration: '18 months',
    client: 'Prime Living Ltd',
    budget: '$12M',
    technologies: ['Reinforced Concrete', 'Thermal Insulation', 'Smart Home Systems', 'Landscaping'],
    images: ['/images/projects/placeholder.svg'],
    status: 'completed',
  },
  {
    id: 'namanve-industrial',
    title: 'Namanve Industrial Park',
    description: 'Development of a 100-acre industrial park with warehouses, factories and supporting infrastructure for manufacturing operations.',
    category: 'Industrial',
    location: 'Namanve, Uganda',
    duration: '30 months',
    client: 'Uganda Investment Authority',
    budget: '$60M',
    technologies: ['Steel Structures', 'Precast Concrete', 'Utilities Infrastructure', 'Road Network'],
    images: ['/images/projects/placeholder.svg'],
    status: 'ongoing',
  },
  {
    id: 'gulu-school',
    title: 'Gulu Model Secondary School',
    description: 'Construction of a modern secondary school with classrooms, laboratories, library, sports facilities and dormitories.',
    category: 'Schools',
    location: 'Gulu, Uganda',
    duration: '12 months',
    client: 'Ministry of Education',
    budget: '$5M',
    technologies: ['Reinforced Concrete', 'Prefab Components', 'Solar Power', 'Water Harvesting'],
    images: ['/images/projects/placeholder.svg'],
    status: 'completed',
  },
  {
    id: 'mbarara-hospital',
    title: 'Mbarara Regional Hospital',
    description: 'Expansion of regional referral hospital including new wards, operating theatres, diagnostic center and outpatient facilities.',
    category: 'Hospitals',
    location: 'Mbarara, Uganda',
    duration: '20 months',
    client: 'Ministry of Health',
    budget: '$20M',
    technologies: ['Reinforced Concrete', 'Medical Gas Systems', 'HVAC', 'Backup Power'],
    images: ['/images/projects/placeholder.svg'],
    status: 'ongoing',
  },
  {
    id: 'kasese-road',
    title: 'Kasese – Fort Portal Road',
    description: 'Upgrading and tarmacking of 80km road connecting Kasese to Fort Portal, improving trade and access to tourism destinations.',
    category: 'Roads',
    location: 'Western Uganda',
    duration: '24 months',
    client: 'Uganda National Roads Authority',
    budget: '$40M',
    technologies: ['Asphalt Concrete', 'Drainage Structures', 'Culverts', 'Road Furniture'],
    images: ['/images/projects/placeholder.svg'],
    status: 'ongoing',
  },
]

export const PROJECT_CATEGORIES = [
  'All',
  'Residential',
  'Commercial',
  'Industrial',
  'Infrastructure',
  'Roads',
  'Schools',
  'Hospitals',
]
