import type { Service } from '../types'

export const SERVICES: Service[] = [
  {
    id: 'building-construction',
    title: 'Building Construction',
    description: 'Comprehensive building construction services for residential, commercial and industrial structures. We deliver quality buildings that stand the test of time.',
    icon: 'Building2',
    image: '/images/services/building-construction.svg',
    category: 'construction',
  },
  {
    id: 'civil-engineering',
    title: 'Civil Engineering',
    description: 'Full-service civil engineering including structural design, site development, and infrastructure planning for complex projects.',
    icon: 'Blueprint',
    image: '/images/services/civil-engineering.svg',
    category: 'engineering',
  },
  {
    id: 'road-construction',
    title: 'Road Construction',
    description: 'Highway and road construction services from earthworks to asphalt paving, ensuring durable and safe transportation networks.',
    icon: 'Route',
    image: '/images/services/road-construction.svg',
    category: 'infrastructure',
  },
  {
    id: 'bridge-construction',
    title: 'Bridge Construction',
    description: 'Design and construction of bridges, flyovers and elevated structures using advanced engineering techniques.',
    icon: 'Bridge',
    image: '/images/services/bridge-construction.svg',
    category: 'infrastructure',
  },
  {
    id: 'water-projects',
    title: 'Water Projects',
    description: 'Water supply systems, treatment plants, dams and irrigation infrastructure for communities and industries.',
    icon: 'Droplets',
    image: '/images/services/water-projects.svg',
    category: 'infrastructure',
  },
  {
    id: 'commercial-buildings',
    title: 'Commercial Buildings',
    description: 'Office complexes, shopping malls, hotels and commercial centers designed for functionality and aesthetic appeal.',
    icon: 'Store',
    image: '/images/services/commercial-buildings.svg',
    category: 'construction',
  },
  {
    id: 'residential-buildings',
    title: 'Residential Buildings',
    description: 'Quality residential developments including apartments, housing estates and luxury homes tailored to client needs.',
    icon: 'Home',
    image: '/images/services/residential-buildings.svg',
    category: 'construction',
  },
  {
    id: 'industrial-construction',
    title: 'Industrial Construction',
    description: 'Factories, warehouses, processing plants and industrial facilities built to meet rigorous operational requirements.',
    icon: 'Factory',
    image: '/images/services/industrial-construction.svg',
    category: 'construction',
  },
  {
    id: 'steel-structures',
    title: 'Steel Structures',
    description: 'Design and erection of steel frameworks, warehouses, stadiums and industrial steel buildings.',
    icon: 'Building2',
    image: '/images/services/steel-structures.svg',
    category: 'construction',
  },
  {
    id: 'renovations',
    title: 'Renovations & Refurbishment',
    description: 'Complete renovation services bringing new life to existing structures with modern designs and improved functionality.',
    icon: 'Wrench',
    image: '/images/services/renovations.svg',
    category: 'construction',
  },
  {
    id: 'project-management',
    title: 'Project Management',
    description: 'End-to-end project management ensuring timely delivery, budget control and quality assurance across all construction phases.',
    icon: 'ClipboardList',
    image: '/images/services/project-management.svg',
    category: 'consultancy',
  },
  {
    id: 'interior-fitout',
    title: 'Interior Fit-Out',
    description: 'Premium interior fit-out services for offices, retail spaces, hotels and residential properties.',
    icon: 'Ruler',
    image: '/images/services/interior-fitout.svg',
    category: 'construction',
  },
  {
    id: 'land-survey',
    title: 'Land Surveying',
    description: 'Professional land surveying services including topographic surveys, boundary determination and construction staking.',
    icon: 'Compass',
    image: '/images/services/land-survey.svg',
    category: 'consultancy',
  },
  {
    id: 'architecture',
    title: 'Architecture & Design',
    description: 'Innovative architectural design services combining functionality, sustainability and aesthetic excellence.',
    icon: 'PencilRuler',
    image: '/images/services/architecture.svg',
    category: 'consultancy',
  },
  {
    id: 'consultancy',
    title: 'Consultancy Services',
    description: 'Strategic construction consultancy including feasibility studies, cost estimation and technical advisory.',
    icon: 'Briefcase',
    image: '/images/services/consultancy.svg',
    category: 'consultancy',
  },
]

export const SERVICE_CATEGORIES = [
  { id: 'all', label: 'All Services' },
  { id: 'construction', label: 'Construction' },
  { id: 'infrastructure', label: 'Infrastructure' },
  { id: 'engineering', label: 'Engineering' },
  { id: 'consultancy', label: 'Consultancy' },
]
